### ISSUE TITLE
Squidpy: NameError 'typing' is not defined

### ISSUE THREAD

**Issue by dbdimitrov** [theislab/squidpy#292]
Hi,

First, congratulations for the great tool and manuscript.

I do have a question. I updated Squidpy to its latest version and since then I am unable to start it in my base Python.
I get the following error:

```
import squidpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbdimitrov/anaconda3/lib/python3.8/site-packages/squidpy/__init__.py", line 10, in <module>
    from squidpy import datasets
  File "/home/dbdimitrov/anaconda3/lib/python3.8/site-packages/squidpy/datasets/__init__.py", line 1, in <module>
    from squidpy.datasets._image import *  # noqa: F403
  File "/home/dbdimitrov/anaconda3/lib/python3.8/site-packages/squidpy/datasets/_image.py", line 31, in <module>
    var._create_function(name, glob_ns=globals())
  File "/home/dbdimitrov/anaconda3/lib/python3.8/site-packages/squidpy/datasets/_utils.py", line 57, in _create_function
    exec(
  File "<string>", line 1, in <module>
NameError: name 'typing' is not defined

```
Yet, it works perfectly fine in iPython (i.e. Jupyter) on the same environment, same Python version, same path. Any ideas?

Thanks in advance!

**Comment by giovp** [comment]
hi @dbdimitrov 
thanks for trying it out! I think you were one who had early access right? How did youinstall it?
if you did from cloning this repo, I would suggest you to remove and reclone it and install it from a fresh clone. Alternatively, try to install with pip, possibly in a fresh conda environemnt. 
Let me know how that goes!

**Comment by dbdimitrov** [comment]
Hi @giovp,

Yes, I had early access - thanks a lot for that. Also, thanks for the promptness of your response.

Indeed, it worked just fine in a new environment :)

Thanks.

**Comment by giovp** [comment]
Thank you!,I'll close this for now, feel free to reopen!
