### ISSUE TITLE
Interactive visualisation of image features does not work

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy#334]
### Description

Napari visualisation of extracted image features does not work (I think because "features" is saved as a pandas table)

### Minimal reproducible example

```python
import squidpy as sq
import napari
img = sq.datasets.visium_hne_image_crop()
adata = sq.datasets.visium_hne_adata_crop()
sq.im.calculate_image_features(adata, img, layer='image', key_added='features')
%gui qt
img.interactive(adata)
```
then, selecting "features" from "obsm", results in the following error:

### Traceback

<details>

```pytb
Traceback (most recent call last):
  File "/Users/hannah.spitzer/projects/spatial_scanpy/squidpy/squidpy/pl/_interactive/_widgets.py", line 133, in _onAction
    vec, name = self._getter(item, index=self.getIndex())
  File "/Users/hannah.spitzer/projects/spatial_scanpy/squidpy/squidpy/pl/_utils.py", line 223, in decorator
    res, fmt = fn(self, *args, **kwargs)
  File "/Users/hannah.spitzer/projects/spatial_scanpy/squidpy/squidpy/pl/_utils.py", line 407, in get_obsm
    return (res if res.ndim == 1 else res[:, index]), self._format_key(name, layer_modifier=False, index=index)
  File "/Users/hannah.spitzer/opt/miniconda3/envs/squidpy/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/hannah.spitzer/opt/miniconda3/envs/squidpy/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), 0)' is an invalid key
```

</details>

### Version

master

**Comment by michalk8** [comment]
You're right, it wasn't supported; it should work now.
