### ISSUE TITLE
Retrieve matplotlib figure instance from plot function

### ISSUE THREAD

**Issue by jo-mueller** [theislab/squidpy#481]
Hi all,

I was wondering whether it could be possible to retrieve the matplotlib figure instance created within a nhood enrichment test, or - even better - pass a matplotlib axes object to `sq.gr.nhood_enrichment()` to allow some more customized plotting?

Thanks in advance!

**Comment by giovp** [comment]
Hi @jo-mueller 

thanks for your interest in Squidpy

great suggestion, we might able to include it for next release. ofc if you'd like to submit PR also very much appreciated!

**Comment by jo-mueller** [comment]
Hi @giovp ,

thanks for the offer! I think the easiest way would be to add an `ax` keyword to the `nhood_enrichment()` function, which would then be passed on to `_heatmap()`. Passing an `ax` keyword would offer the advantage of not meddling with the function returns. 

I'll try myself with an implementation.

**Comment by giovp** [comment]
I think it makes a lot of sense indeed, if you can draft something I'd be happy to help you out, thanks a lot!
You can see contributing infos here: https://github.com/theislab/squidpy/blob/master/CONTRIBUTING.rst

if you have issues with pre-commit and can't solve some errors, no worry just `git commit --no-verify` and it will skip pre-commits checks that we can fix later.

**Comment by jo-mueller** [comment]
Alright, I think I have it implemented and tests pass locally (only for the heatmap though - I guess it could make sense for the other plot functions, too?)

One issue I'm seeing though:
Building the documentation fails on my machine; `tox -e docs` gives me an error which is probably the same as in https://github.com/theislab/scanpy/issues/2108:

```
Traceback (most recent call last):
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\sphinx\config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\docs\source\conf.py", line 25, in <module>
    import squidpy  # noqa: E402
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\squidpy\__init__.py", line 1, in <module>
    from squidpy import gr, im, pl, datasets
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\squidpy\gr\__init__.py", line 2, in <module>
    from squidpy.gr._build import spatial_neighbors
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\squidpy\gr\_build.py", line 8, in <module>
    from scanpy import logging as logg
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\scanpy\__init__.py", line 14, in <module>
    from . import tools as tl
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\scanpy\tools\__init__.py", line 17, in <module>
    from ._sim import sim
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\scanpy\tools\_sim.py", line 23, in <module>
    from .. import _utils, readwrite, logging as logg
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\scanpy\readwrite.py", line 10, in <module>
    import tables
  File "C:\Users\johamuel\Documents\BiAPoL\Projects\squidpy\.tox\docs\lib\site-packages\tables\__init__.py", line 45, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: DLL load failed while importing utilsextension: The specified module could not be found.
```

When installing squidpy, installing h5py and pytables separately with conda works but I'm not sure how to fix it when installing it through tox. I'm on Python 3.8.12
