### ISSUE TITLE
Error running sq.gr.nhood_enrichment: RuntimeError: There is no current event loop in thread 'MainProcess'

### ISSUE THREAD

**Issue by mdu4003** [theislab/squidpy#487]
Hello, 
I am analyzing Vectra images using adata generated in pathml. 
When running this command on a mac using pycharm: 
sq.gr.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis")
I have this error: 
File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainProcess'.
Is it fixable? I am attaching the events.py file (it is in pdf) in which the error originates, just in case it is only a matter of modifying it. 
Thank you very much!!
[events.py.pdf](https://github.com/theislab/squidpy/files/8308069/events.py.pdf)

**Comment by michalk8** [comment]
Hi @mdu4003 , we don't use `asyncio` in `squidpy`, not sure where the error originates from.
Could you please post the full traceback of the error? The file you've attached isn't helpful, since it's a part of Python by default.

**Comment by mdu4003** [comment]
Hi @michalk8, Thank you very much for your quick response. 
I work with Python 3.8. And this is the version of squidpy: 
# Name                    Version                   Build  Channel
squidpy                   1.1.2                    pypi_0    pypi

Please, see here the traceback of the error I get: 

sq.gr.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis")
  0%|          | 0/1000 [00:00<?, ?/s]Traceback (most recent call last):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-860-bcb8ad0f1a69>", line 1, in <module>
    sq.gr.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis")
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/gr/_nhood.py", line 174, in nhood_enrichment
    perms = parallelize(
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/_utils.py", line 168, in wrapper
    res = jl.Parallel(n_jobs=n_jobs, backend=backend)(
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/gr/_nhood.py", line 402, in _nhood_enrichment_helper
    queue.put(Signal.UPDATE)
  File "<string>", line 2, in put
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/multiprocessing/managers.py", line 243, in serve_client
    request = recv()
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/__init__.py", line 12, in <module>
    import squidpy.im
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/im/__init__.py", line 2, in <module>
    from squidpy.im._feature import calculate_image_features
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/im/_feature.py", line 15, in <module>
    from squidpy.im._container import ImageContainer
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/squidpy/im/_container.py", line 28, in <module>
    import xarray as xr
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/xarray/tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/xarray/backends/__init__.py", line 6, in <module>
    from .cfgrib_ import CfGribDataStore
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/xarray/backends/cfgrib_.py", line 16, in <module>
    from .locks import SerializableLock, ensure_lock
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/xarray/backends/locks.py", line 13, in <module>
    from dask.distributed import Lock as DistributedLock
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/dask/distributed.py", line 11, in <module>
    from distributed import *
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/__init__.py", line 7, in <module>
    from .actor import Actor, ActorFuture
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/actor.py", line 5, in <module>
    from .client import Future
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/client.py", line 59, in <module>
    from .batched import BatchedSend
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/batched.py", line 10, in <module>
    from .core import CommClosedError
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/core.py", line 28, in <module>
    from .comm import (
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/comm/__init__.py", line 25, in <module>
    _register_transports()
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/comm/__init__.py", line 17, in _register_transports
    from . import inproc, tcp, ws
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/comm/tcp.py", line 387, in <module>
    class BaseTCPConnector(Connector, RequireEncryptionMixin):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/distributed/comm/tcp.py", line 389, in BaseTCPConnector
    _resolver = netutil.ExecutorResolver(close_executor=False, executor=_executor)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/tornado/util.py", line 288, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/tornado/netutil.py", line 427, in initialize
    self.io_loop = IOLoop.current()
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/tornado/ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainProcess'.
---------------------------------------------------------------------------

**Comment by michalk8** [comment]
The problem seems to be with ``joblib`` and ``dask``, there are a few things you can try:
- pass `show_progress_bar=False` since the error shows up when trying to update progress bar in the main process as `sq.gr.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis", show_progress_bar=False)`
- change the backend to `"threading"` as `sq.gr.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis", backend="threading")`

**Comment by mdu4003** [comment]
Hello, 
I tried with backend="threading", but I still have the same issue. 
However, it seems to be solved if I add show_progress_bar=False. 
Now the problem is that I do not see any plot after:

sq.pl.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis", method="ward")

I do not see any traceback. Only no plot after running the command. 
Any suggestion? Thank you so much!

**Comment by michalk8** [comment]
> I do not see any traceback. Only no plot after running the command.
Any suggestion? Thank you so much!

This is because we don't call `figure.show()` after the function has been called, since this is usually done in Jupyter automatically, as mentioned here: https://matplotlib.org/3.5.1/api/_as_gen/matplotlib.pyplot.show.html

You can try running:
```python
import matplotlib.pyplot as plt
...
sq.pl.nhood_enrichment(adata_combined_noenhc, cluster_key="cd8_enrichment_analysis", method="ward")
plt.gcf().show()  # `gcf` stands for `get current figure`
```

**Comment by mdu4003** [comment]
Got it!. 
Solved! thank you very, very much, @michalk8!!
I really appreciate your help. 
Have a nice weekend!

**Comment by mdu4003** [comment]
Sorry, Only one more thing. The plot is cut and I can not see the names and scale.

<img width="484" alt="Screen Shot 2022-03-19 at 11 27 06 AM" src="https://user-images.githubusercontent.com/83671153/159127296-abde5e03-fcdb-4bfe-8eb0-b449e99aaa13.png">

**Comment by michalk8** [comment]
> Sorry, Only one more thing. The plot is cut and I can not see the names and scale.

What `matplotlib` backend are you using? Mine is `QtAgg` and in an example data, it's fine.
You can see it by running:
```python
import matplotlib
matplotlib.get_backend()
# to set it, run:
matplotlib.use("QtAgg")
```
In any case, you can also try changing the default `figsize` and `dpi`. Lastly, if none of above work, try saving the figure by passing `save` as e.g. `sq.pl.nhood_enrichment(..., save=my_figure.png)`.

**Comment by mdu4003** [comment]
Saving the file solved the issue. Thank you very much!!
Maybe I should try to use Jupyter Notebook, instead of Pycharm.

Just for your record. 
I am using:
import matplotlib
matplotlib.get_backend()
Out[24]: 'module://backend_interagg'

Tried this:
matplotlib.use("QtAgg"), but got an error. 
matplotlib.use('QtAgg')
Traceback (most recent call last):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-42aea3d4a597>", line 1, in <module>
    matplotlib.use('QtAgg')
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/matplotlib/__init__.py", line 1144, in use
    plt.switch_backend(name)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/diazmeco/opt/anaconda3/envs/pathml/lib/python3.8/site-packages/matplotlib/backends/qt_compat.py", line 128, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding.

I got my plot by saving it!. Thank you very much!!!

**Comment by michalk8** [comment]
> I got my plot by saving it!. Thank you very much!!!

Glad this works, think this can be closed then.
